const holidays = {
    "08": {
        "01": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "02": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "03": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "04": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "23": ["aaaa"],
        "24": ["Dzień Windowsa"],
        "25": ["120. rocznica śmierci Nietzschego"],
        "26": ["Filipiński Dzień Bohaterów"],
        "27": ["Dzień Tira", "Święto Niepodległości Mołdawii"],
        "28": ["Święto Lotnictwa Polskiego"],
        "29": ["Dzień Strażnika Gminnego i Miejskiego"],
        "30": ["Międzynarodowy Dzień Pamięci o Osobach Zaginionych"],
        "31": ["Dzień Blogów"]

    },
    "09": {
        "01": ["Pierwszy Dzień Szkoły"],
        "02": ["Dzień Dużego Rozmiaru"],
        "03": ["Dzień Wersalskiego Pokoju"],
        "04": ["Dzień Imigranta"],
        "05": ["Dzień Postaci z Bajek"],
        "06": ["Święto niepodległości Eswatini"],
        "07": ["Dzień Zwycięstwa w Mozambiku"],
        "08": ["Dzień Dobrej Wiadomości"],
        "09": ["Międzynarodowy Dzień Urody"],
        "10": ["Światowy Dzień Zapobiegania Samobójstwom"],
        "11": ["Dzień Histerii i Egocentryzmu w USA"],
        "12": ["Dzień Programisty"],
        "13": ["Dzień Całowania Chłopaków w Usta"],
        "14": ["Wspomnienie Podwyższenia Krzyża Świętego"],
        "15": ["Dzień olewania systemu"],
        "16": ["Dzień Bluesa"],
        "17": ["Dzień Szacunku dla Ludzi Starszych"],
        "18": ["Międzynarodowy Dzień Geologa"],
        "19": ["Międzynarodowy Dzień Mówienia jak Pirat"],
        "20": ["Dzień Niepodległości Osetii Południowej"],
        "21": ["Dzień Służby Celnej"],
        "22": ["Dzień bez Samochodu"],
        "23": ["Dzień Śliwki"],
        "24": ["Dzień Grzyba"],
        "25": ["Dzień Budowlańca"],
        "26": ["Dzień Całowania Dziewczyn"],
        "27": ["Doroczny Dzień Wymiany Oleju do Smażenia Frytek w Barach Szybkiej Obsługi"],
        "28": ["Światowy Dzień Morza"],
        "29": ["Dzień Hipochondryka"],
        "30": ["Dzień Chłopaka"],
    },
    "10": {
        "01": ["Międzynarodowy Dzień Wegetarianizmu"],
        "02": ["Międzynarodowy Dzień bez Przemocy"],
        "03": ["Dzień bez Kamizelki Kuloodpornej"],
        "04": ["Międzynarodowy Dzień Zwierząt"],
        "05": ["Międzynarodowy Dzień Belfra-Tępiciela"],
        "06": ["Światowy Dzień Mieszkalnictwa"],
        "07": ["Dzień Matki Bożej Różańcowej"],
        "08": ["Dzień Marynarki Wojennej Peru"],
        "09": ["Światowy Dzień Poczty i Znaczka Pocztowego"],
        "10": ["Dzień Kolejarza"],
        "11": ["Dzień Wychodzenia z Szafy"],
        "12": ["Dzień Bezpiecznego Komputera"],
        "13": ["Dzień Bez Bielizny"],
        "14": ["Dzień Edukacji Narodowej"],
        "15": ["Światowy Dzień Mycia Rąk"],
        "16": ["Światowy Dzień Żywności"],
        "17": ["Międzynarodowy Dzień Walki z Ubóstwem"],
        "18": ["Dzień Listonosza"],
        "19": ["Dzień Normalizacji"],
        "20": ["Międzynarodowy Dzień Kontrolera Ruchu Lotniczego"],
        "21": ["Dzień Bez Skarpetek"],
        "22": ["Dzień Caps Locka"],
        "23": ["Dzień Mola"],
        "24": ["Międzynarodowe Święto Roweru"],
        "25": ["Dzień Kundelka"],
        "26": ["Światowy Dzień Donacji i Transplantacji"],
        "27": ["Dzień Lesbijki"],
        "28": ["Dzień Odpoczynku dla Zszarganych Nerwów"],
        "29": ["Światowy Dzień Udaru Mózgu"],
        "30": ["Dzień Spódnicy"],
        "31": ["Halloween"]
    },
    "11": {
        "01": ["Wszystkich Świętych"],
        "02": ["Dzień Zaduszny"],
        "03": ["Święto Myśliwych"],
        "04": ["Dzień Taniego Wina"],
        "05": ["Dzień Postaci z Bajek"],
        "06": ["Międzynarodowy Dzień Zapobiegania Eksploatacji Środowiska Naturalnego podczas Wojen i Konfliktów Zbrojnych"],
        "07": ["Dzień Feministek"],
        "08": ["Święto konstytucji Mikronezji"],
        "09": ["Światowy Dzień Gry Wstępnej"],
        "10": ["Dzień Młodzieży"],
        "11": ["Narodowe Święto Niepodległości"],
        "12": ["Światowy Dzień Bicia Rekordów"],
        "13": ["Dzień Łapania za Cycki lub za Tyłek"],
        "14": ["Dzień Wyznawania Miłości"],
        "15": ["Święto Wojskowego Centrum Geograficznego "],
        "16": ["Dzień Tolerancji"],
        "17": ["Dzień Studenta"],
        "18": ["Światowy Dzień Rzucania Palenia Tytoniu"],
        "19": ["Dzień Toalet"],
        "20": ["Dzień Praw Dziecka"],
        "21": ["Światowy Dzień Życzliwości i Pozdrowień"],
        "22": ["Dzień Kredki"],
        "23": ["Dzień Licealisty"],
        "24": ["Katarzynki"],
        "25": ["Dzień Pluszowego Misia"],
        "26": ["Święto Niepodległości Mongolii"],
        "27": ["Święto mniejszości etnicznej Indii"],
        "28": ["Dzień Pocałunku"],
        "29": ["Dzień Podchorążego"],
        "30": [" Dzień Białych Skarpetek"],
    }
  }
  
  export default holidays