const holidays = {
    "08": {
        "01": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "02": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "03": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "04": ["Narodowy Dzień Pamięci Powstania Warszawskiego (Dzień Pamięci Warszawy)"],
        "23": ["aaaa"],
        "24": ["Dzień Windowsa"],
        "25": ["120. rocznica śmierci Nietzschego"],
        "26": ["Filipiński Dzień Bohaterów"],
        "27": ["Dzień Tira", "Święto Niepodległości Mołdawii"],
        "28": ["Święto Lotnictwa Polskiego"],
        "29": ["Dzień Strażnika Gminnego i Miejskiego"],
        "30": ["Międzynarodowy Dzień Pamięci o Osobach Zaginionych"],
        "31": ["Dzień Blogów"]

    },
    "09": {
        "01": ["Pierwszy Dzień Szkoły"],
        "02": ["Dzień Dużego Rozmiaru"],
        "03": ["Dzień Wersalskiego Pokoju"],
        "04": ["Dzień Imigranta"],
        "05": ["Dzień Postaci z Bajek"],
        "06": ["Święto niepodległości Eswatini"],
        "07": ["Dzień Zwycięstwa w Mozambiku"],
        "08": ["Dzień Dobrej Wiadomości"],
        "09": ["Międzynarodowy Dzień Urody"],
        "10": ["Światowy Dzień Zapobiegania Samobójstwom"],
        "11": ["Dzień Histerii i Egocentryzmu w USA"],
        "12": ["Dzień Programisty"],
        "13": ["Dzień Całowania Chłopaków w Usta"],
        "14": ["Wspomnienie Podwyższenia Krzyża Świętego"],
        "15": ["Dzień olewania systemu"],
        "16": ["Dzień Bluesa"],
        "17": ["Dzień Szacunku dla Ludzi Starszych"],
        "18": ["Międzynarodowy Dzień Geologa"],
        "19": ["Międzynarodowy Dzień Mówienia jak Pirat"],
        "20": ["Dzień Niepodległości Osetii Południowej"],
        "21": ["Dzień Służby Celnej"],
        "22": ["Dzień bez Samochodu"],
        "23": ["Dzień Śliwki"],
        "24": ["Dzień Grzyba"],
        "25": ["Dzień Budowlańca"],
        "26": ["Dzień Całowania Dziewczyn"],
        "27": ["Doroczny Dzień Wymiany Oleju do Smażenia Frytek w Barach Szybkiej Obsługi"],
        "28": ["Światowy Dzień Morza"],
        "29": ["Dzień Hipochondryka"],
        "30": ["Dzień Chłopaka"],
    }
  }
  
  export default holidays